name: Build Chromium for Android 6

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions将在Ubuntu虚拟环境上运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up depot_tools
        run: |
          # 安装Depot Tools（Chromium构建工具）
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:$PWD/depot_tools"

      - name: Install dependencies
        run: |
          # 更新系统并安装必要的依赖
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3 \
            python3-pip \
            python3-setuptools \
            git \
            curl \
            clang \
            libtool \
            pkg-config \
            libgtk2.0-dev \
            libnss3-dev \
            libxslt1-dev \
            libxss1
            sudo add-apt-repository ppa:gnome3-team/gnome3 -y
            sudo apt-get update
            sudo apt-get install libgconf-2-4

      - name: Fetch Chromium source code
        run: |
          # 创建Chromium工作目录并获取Android源代码
          mkdir ~/chromium && cd ~/chromium
          fetch --nohooks android
          cd src

      - name: Install build dependencies
        run: |
          # 安装Chromium所需的所有构建依赖
          build/install-build-deps.sh

      - name: Set up GN args
        run: |
          # 设置构建配置（使用Android 6）
          gn gen out/Default --args='target_os="android" target_cpu="arm64" use_remoteexec=true android_static_analysis="build_server"'

      - name: Build Chromium for Android
        run: |
          # 使用Ninja构建Chromium APK
          autoninja -C out/Default chrome_public_apk

      - name: Install Chromium APK on Android
        run: |
          # 安装并启动Chromium APK
          adb devices
          autoninja -C out/Default chrome_public_apk install

      - name: Run Tests (optional)
        run: |
          # 可选：运行Chromium的单元测试
          autoninja -C out/Default chrome/test:unit_tests
