name: Build Chrome for Android 6 (ARM64)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository containing Chromium/Chrome source code
    - name: Checkout Chromium source code
      uses: actions/checkout@v2

    # Set up required dependencies for building Chromium
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-dev \
          g++ \
          curl \
          cmake \
          gn \
          clang

    # Install Android NDK and SDK for building Chrome for Android
    - name: Set up Android SDK
      run: |
        sudo apt-get install -y openjdk-8-jdk
        
        # Download and unzip SDK tools
        curl -sS https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o sdk-tools.zip
        unzip sdk-tools.zip -d $HOME/android-sdk
        
        # Check the contents of the cmdline-tools directory before moving files
        echo "Contents of cmdline-tools before moving:"
        ls -la $HOME/android-sdk/cmdline-tools
        
        # Create the directory structure for 'latest'
        mkdir -p $HOME/android-sdk/cmdline-tools/latest/bin
        mkdir -p $HOME/android-sdk/cmdline-tools/latest/lib
        
        # Move individual files and subdirectories (not the entire bin directory)
        mv $HOME/android-sdk/cmdline-tools/bin/* $HOME/android-sdk/cmdline-tools/latest/bin/
        mv $HOME/android-sdk/cmdline-tools/lib/* $HOME/android-sdk/cmdline-tools/latest/lib/
        mv $HOME/android-sdk/cmdline-tools/source.properties $HOME/android-sdk/cmdline-tools/latest/

        # Check the contents of cmdline-tools after moving files
        echo "Contents of cmdline-tools after moving:"
        ls -la $HOME/android-sdk/cmdline-tools/latest
        
        # Accept licenses and install necessary SDK components
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-23" "build-tools;29.0.3" "ndk;21.4.7075529"

    # Build Chromium/Chrome for ARM64 Android
    - name: Build Chromium for ARM64 Android
      run: |
        # Verify that the Chromium source has been correctly checked out
        echo "Current directory contents:"
        ls -la
        
        # If the Chromium source is in a specific subdirectory, modify this path accordingly
        # For example, if the Chromium source is in the 'src' directory, use:
        # cd src
        # Or if it's directly in the repository root, no need to change directory
        cd $GITHUB_WORKSPACE

        # Install sysroot for ARM64 architecture
        python3 build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
        ./build/install-build-deps.sh

        # Generate build files using gn for ARM64
        gn gen out/Default --args="target_os=\"android\" target_cpu=\"arm64\" is_debug=false android_sdk_root=\"$HOME/android-sdk\""

        # Run ninja to build the chrome executable for ARM64
        ninja -C out/Default chrome
